server:
  port: 4001  #配置服务端口

spring:
  application:
    name: AliCloud-provider-payment4001 #服务名称-服务之间使用名称进行通讯
    # 数据库访问配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-learn?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true


#注册到zookeeper服务中心
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181














